security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User\User:
            algorithm: auto
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User\User
                property: email
    access_denied_url: /
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            pattern: ^/.
            security: false
        user_create:
            pattern: ^/user/create/.
            security: false
        user_sign_in:
            pattern: ^/user/sign-in/.
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators: 
                - App\Security\Authenticator\UserTokenAuthenticator
